version: "3.9"

services:
  backend:
    build:
      args:
        user: tractian-user
        uid: 2000
      context: ./
    tty: true
    ports:
      - 3000:3000
    volumes:
    - ./:/tractian-api
    command: sh -c "yarn install && tail -f /dev/null"
  mongodb:
    image: mongo:5.0.5
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test-password


